# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GdERkt-FF987SkZZfEZl0wCltcmhuIEf
"""

nilai = set({3,6,9,2,5,7})
a = nilai.update({1,2,3,4,5,6,7,8,9,10})
print(nilai)

nilai = set({3,6,9,2,5,7})
a = nilai.update({1,4,8,10})
print(nilai)
b = nilai.difference_update({1,3,4,5,7,8,10})
print(nilai)

A = {100,7,8}
B = {200,4,5}
C = {300,2,3}
D = {100,200,300}
print(A.intersection(D))
print(B.intersection(D))
print(C.intersection(D))
print(A.intersection(B).intersection(C).intersection(D))

A = {100,7,8}
B = {200,4,5}
C = {300,2,3}
D = {100,200,300}
print(A.union(B))
print(B.union(C))
print(B.union(C).union(D))
print(A.union(B).union(C).union(D))

A = {'a', 'b', 'c', 'd'}
B = {'c', 'd', 'e'}
C = {}
print(A.symmetric_difference(B))
print(B.symmetric_difference(A))
print(A.symmetric_difference(C))
print(B.symmetric_difference(C))

A = {'a', 'b', 'c', 'd'}
B = {'c', 'd', 'e'}
C = {}
print(A.difference(B))
print(B.difference(A))
print(A.difference(C))
print(B.difference(C))

